### ISSUE TITLE
examples > BT

### ISSUE THREAD

**Issue by octopusengine** [TomasRoj/OctopusLab-Library#2]
CHARACTERISTIC_UUID > dynamic ESP32 "device UID " ?

**Comment by TomasRoj** [comment]
Hey, Thanks for your issue. I will look at it and fix it. For the next time, please don't do this type of issue. Describe your problem more so everybody can understand it. If you are not fully with this, please use the issue template option.

**Comment by TomasRoj** [comment]
As we desribed in the cat, there is link for generating random UID > read more before publishing new issue.
