### ISSUE TITLE
Pin for different boards

### ISSUE THREAD

**Issue by petrkr** [TomasRoj/OctopusLab-Library#3]
How you will recognize (and change) pinout for different boards, if you hard-coded this one? Remember IoT Board does not have motor pins, but have FET/Relay instead.

**Comment by TomasRoj** [comment]
Hi,

I don't understand that "hard-coded" poem but I understand your question. Currently, we are all developing full support for the robot board module (this includes examples - with comments, have correct names for all the pins, etc.). I don't fully know what will be the next step. This is a good question to consult later on when all the required bugs and features will be completed. I will leave this issue open so everybody will have the option to reply and tell what he thinks.

**Comment by petrkr** [comment]
You should prepare pinout before, because later you will have really hard to rewrite library to support such thing. You should not rewrite it's API once it's released. You can add, but will be hard to remove or change. You MUST keep library compatible with first version. So it's better to think about API now, no later.

**Comment by petrkr** [comment]
For example, basic octopus library should support only "led blink" because it's board independent thing. Also it should be abstract class (or interface) for other boards. So you will only add board-specific things.

Like you have 

OctopusLibBase:
 led_blink()

OctopusLibRobotBoardV1: (parent class OctopusLibBase)
  motor_start(motor1)
  
so if you will do instance of `OctopusLibRobotBoardV1` you will get led_blink and motor_start.

Also pin definitions should be for motors in RobotBoard class, but for builtin led it can be already in Base

**Comment by TomasRoj** [comment]
Hey, 

I don't fully understand what you are saying right now. If we will release the library at its own to the Arduino IDE library manager it will not be a problem to change it. The library manager has own "radar script" which checks for the new release of the library. If it finds the new version (ex. v1.1) it will take it and upload it to the index. It just needs a new release. for that abstract class - yes its great idea to do it. But I don't fully understand this topic at all so it will be better to leave it up to you.

**Comment by petrkr** [comment]
I talk about how lib should be programmed. Like there are more boards. More boards have different pinouts and peripheries. (Such as robot have motors, servos, IoT have Relay, PWM/Fet) and you can not have everything in one big library. You have to separate it to more classes. But in generic programming you have to use Abstract classes for base and then do Inheritance for specific classes

**Comment by TomasRoj** [comment]
Yes, I understand it now. I didn't do abstract classes so I will have to study it and try to implement it. I will close this issue and add it to the todo list. Thanks 👍

**Comment by petrkr** [comment]
You should not close this issue before it's clear how you will do backward-compatible library. Abstract classes is one of way. If you do not know how do it now, you should do more normal classes instead and do abstract later. Even now it will be just "copy & paste"... Meaning if this issue is to have generic library, which is backward-compatible.

Not like if someone will download version 1.0.0 and then update to 2.0.0 (for example) their's program will stop work due that. You can not do this later. You need to have atleast abstract point of view now.

**Comment by TomasRoj** [comment]
Ok, let's have it opened and I also added to the todo list now.

**Comment by TomasRoj** [comment]
Looks completed due to making abstract classes. Closing.
